server.enable-raft=false
# ????????????
service.vgroup-mapping.my_at_tx_group=default

# Seata Server ????????????
service.default.grouplist=192.168.43.204:8091

# ????????? false?
service.enable-degrade=false
# ??????????? false?
service.disable-global-transaction=false

# ??? RM ??
client.rm.async-commit-buffer-limit=10000
client.rm.lock.retry-internal=10
client.rm.lock.retry-times=30
client.rm.report.retry-count=5
client.rm.table-meta-check-enable=false
client.rm.sql-parser-types=druid

# ??? TM ??
client.tm.commit-retry-count=5
client.tm.rollback-retry-count=5

# ???????? server ????? ????????? camelCase?
store.mode=db
store.db.dbType=mysql
store.db.datasource=hikari
store.db.driverClassName=com.mysql.cj.jdbc.Driver
store.db.url=jdbc:mysql://127.0.0.1:3306/seata?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
store.db.user=root
store.db.password=123456
store.db.minConn=5
store.db.maxConn=30
store.db.globalTable=global_table
store.db.branchTable=branch_table
store.db.lockTable=lock_table
store.db.distributedLockTable=distributed_lock
store.db.queryLimit=1000
store.db.maxWait=5000